#!/bin/sh

lib_failed=0
lib_passed=0
lib_failed_bad=0
lib_tests=0

echo '-- tests start --'
for f in `cat testlist`;
do
  lib_tests=`expr $lib_tests + 1` >/dev/null 2>&1

  ./$f >$f.out 2>&1
  ret=$?

  case $ret in
    0)
      echo passed run $f
      lib_passed=`expr $lib_passed + 1` >/dev/null 2>&1
      ;;
    1)
      echo failed run $f
      lib_failed=`expr $lib_failed + 1` >/dev/null 2>&1
      ;;
    *)
      echo crash run $f
      lib_failed_bad=`expr $lib_failed_bad + 1` >/dev/null 2>&1
      ;;
  esac

  if [ $ret -eq 0 ]
  then
    lib_tests=`expr $lib_tests + 1` >/dev/null 2>&1
    cmp $f.dat $f.exp >/dev/null 2>&1
    ret=$?
    case $ret in
      0)
        echo passed output $f
        lib_passed=`expr $lib_passed + 1` >/dev/null 2>&1
        ;;
      1)
        echo failed output $f
        lib_failed=`expr $lib_failed + 1` >/dev/null 2>&1
        ;;
      *)
        echo crash output $f
        lib_failed_bad=`expr $lib_failed_bad + 1` >/dev/null 2>&1
        ;;
    esac
  fi

done
cat <<EOF
-- tests end --
tests      $lib_tests
passed     $lib_passed
failed     $lib_failed
crashed    $lib_failed_bad
EOF
